<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Thank you</name>
   <tag></tag>
   <elementGuidId>4d3593a1-f880-46f5-ab8a-412e04610f0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/h1</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h1.heading.h1.text-center.heading-thankyou</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>e82fbc8d-735c-42af-9fc0-d5f6329cc34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>heading h1 text-center heading-thankyou</value>
      <webElementGuid>d266996f-c827-4f9a-a21a-5d9a2869c940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thank you!</value>
      <webElementGuid>a06c1bb4-5784-4426-9bac-aed9436ef142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;App&quot;]/div[@class=&quot;body-side--container wrapper&quot;]/div[@class=&quot;mx-auto thankyou-container&quot;]/h1[@class=&quot;heading h1 text-center heading-thankyou&quot;]</value>
      <webElementGuid>45349cd3-71b0-410e-8ef2-f2e60a527e21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/h1</value>
      <webElementGuid>0ceddf62-8b17-4948-be21-13d455793246</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thank you!']/parent::*</value>
      <webElementGuid>c875e3c0-ea46-479e-a908-94b16214a977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>d49c6110-2090-404a-a28d-9387475286df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'Thank you!' or . = 'Thank you!')]</value>
      <webElementGuid>e7ad3104-6745-49be-b8f0-08f87703be32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
