<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__emergencyZipcode</name>
   <tag></tag>
   <elementGuidId>b0c56d70-9877-477f-82da-80bd85dfc449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyZipcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyZipcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3a1a41b-3abc-4fed-8068-3d9ec73fda52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>9c961874-7a30-4f53-bee9-1f40d7aeb2a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>20e2c7fd-8cc9-4b52-ab20-c47e7de9608e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyZipcode</value>
      <webElementGuid>a9c857a6-42df-40a8-9e24-2efecef0adef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: 73301</value>
      <webElementGuid>75a1774d-23fa-48fe-a867-b63b44886523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyZipcode</value>
      <webElementGuid>28cea0d0-50fc-48b0-81be-8bca3d882916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyZipcode&quot;)</value>
      <webElementGuid>0a102521-74a8-418a-abd1-4456055b5942</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyZipcode']</value>
      <webElementGuid>77f2e1ac-13aa-467a-b534-23b93ca1e232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[5]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>ffb88147-b62b-4883-813c-444cbb55ade2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[5]/div/div[3]/div/div[2]/input</value>
      <webElementGuid>a0d5afc1-4420-4005-83cb-e342e8c25331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputEmergencyZipcode' and @placeholder = 'Example: 73301' and @name = 'emergencyZipcode']</value>
      <webElementGuid>9c32d4b5-7ea1-49af-8a59-8a8b43c0d7d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
