<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__emergencyMobileNumber</name>
   <tag></tag>
   <elementGuidId>8222355c-db80-4a01-aa26-6784c05a0d20</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyMobileNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyMobileNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3971d8ef-257b-4810-8ae3-1f8fc144cd47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>7a5a57c7-21eb-4b89-9ac4-d80514f7c88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>71c3c9b9-1f4e-4ee8-a522-e4127e8bfb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyMobileNumber</value>
      <webElementGuid>a0a0870b-3a7f-40bd-9d03-eecd0345091a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>+1 (234) 567-8910</value>
      <webElementGuid>b375caf1-80ba-4be5-b109-99b90adfa3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyMobileNumber</value>
      <webElementGuid>dcb8693d-3bc1-46bb-8c5d-34e01991207a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyMobileNumber&quot;)</value>
      <webElementGuid>1dc4beb6-efd7-49b9-8d43-6fe017dd7cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyMobileNumber']</value>
      <webElementGuid>091ed46e-724e-4774-a644-be64963adc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>4fd8c3ff-f4fd-4ae5-b5de-8ba2d22ec1ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/div/div[2]/input</value>
      <webElementGuid>310d6b54-626f-49f0-81e5-01d6b6f87ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @id = 'inputEmergencyMobileNumber' and @placeholder = '+1 (234) 567-8910' and @name = 'emergencyMobileNumber']</value>
      <webElementGuid>f7d47748-9ea7-441b-9545-5a6e87633024</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
