<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__emergencyAddress</name>
   <tag></tag>
   <elementGuidId>ac6daf01-fcf4-4f73-8e58-b14907bc8d57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmergencyAddress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyAddress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4461d90-7b4c-46ce-924a-6b0116866393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>f7beb3e0-f699-4026-9a76-156570d4847d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f533f32a-3a4e-45e7-bb7a-9d0c7d6222ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyAddress</value>
      <webElementGuid>adb53f64-afb7-41d6-9dc1-31ff35176576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Example: 4910 Pin Oak Drive NY</value>
      <webElementGuid>932067b9-0f17-487f-994d-9fa484390a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyAddress</value>
      <webElementGuid>d8d03648-4cee-4eeb-abc8-428eb683ece3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyAddress&quot;)</value>
      <webElementGuid>aeabae2b-e93b-4035-b932-dbbfba0f8141</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmergencyAddress']</value>
      <webElementGuid>cc8b2193-b880-49f2-9d6b-a8e16a5f5666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>c583cb8e-b47c-4504-a0f6-69f13b7f4e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>e91cac80-966f-4c77-b6c8-a1b781264226</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputEmergencyAddress' and @placeholder = 'Example: 4910 Pin Oak Drive NY' and @name = 'emergencyAddress']</value>
      <webElementGuid>bfa5a226-3c7f-4071-a030-3fae985f21a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
