<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a city in District of ColumbiaWashington</name>
   <tag></tag>
   <elementGuidId>434d02e3-44c6-423c-97aa-7e317b27f7fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputEmergencyCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ef7e30d2-6a42-4f48-88de-8ed7d898858f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>1226d866-3974-494e-a19f-fc85600a3b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyCity</value>
      <webElementGuid>756cb5e9-ce12-45de-b6b1-c104e6e6189f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyCity</value>
      <webElementGuid>6355b2da-6406-4442-a3ae-4ad1bf29dfed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a city in District of ColumbiaWashington</value>
      <webElementGuid>312eb80b-2063-4a40-ab2b-f4e6a1fd13d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyCity&quot;)</value>
      <webElementGuid>76afbf63-5fa3-4dd0-95e5-1f8a6801060c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputEmergencyCity']</value>
      <webElementGuid>ce9e4369-14c7-4087-8400-84be00d04532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>a9b30ed8-42d8-4c0b-8de5-47f1e023f8a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/following::select[1]</value>
      <webElementGuid>a2c344df-e0e4-4b73-8323-1b2a0f550e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/preceding::select[1]</value>
      <webElementGuid>358911fa-33a6-4b5a-8969-6a1d60f85811</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>197a15ec-2a66-4e1f-aafd-4fee6ee34ef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputEmergencyCity' and @name = 'emergencyCity' and (text() = 'Select a city in District of ColumbiaWashington' or . = 'Select a city in District of ColumbiaWashington')]</value>
      <webElementGuid>e007ca64-98de-431e-91b5-0ef3981fd1cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
