<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Select a city in UtahSalt Lake CityWest Valley CityProvoWest JordanOremSandyOgdenSt. GeorgeLaytonTaylorsvilleSouth JordanLehiLoganMurrayDraperBountifulRivertonRoy</name>
   <tag></tag>
   <elementGuidId>1f3053f1-14f8-43a3-90a0-5bdf92ae157e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputCity']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputCity</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e20061c7-98bc-470f-b86d-e268a4df9fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>cb0f4bcc-a7ef-4cb1-ac02-2e3def341329</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCity</value>
      <webElementGuid>bd6b8032-dd22-448f-ab29-e2d5f2561b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>city</value>
      <webElementGuid>8d4e5599-a156-42a1-b228-08a1e2971c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a city in UtahSalt Lake CityWest Valley CityProvoWest JordanOremSandyOgdenSt. GeorgeLaytonTaylorsvilleSouth JordanLehiLoganMurrayDraperBountifulRivertonRoy</value>
      <webElementGuid>5b8618e2-972d-44c3-b27e-973c44035bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCity&quot;)</value>
      <webElementGuid>d6a69a28-aeee-4753-a21a-a57188b063b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputCity']</value>
      <webElementGuid>e9b18117-9466-4d9d-a167-fa99f66f4863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/div[2]/div[5]/div/div[2]/div/div[2]/select</value>
      <webElementGuid>28a59714-ee5a-4df6-ba53-d6a43f908b7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/following::select[1]</value>
      <webElementGuid>912ab23f-2856-4924-b45a-4df617e6f42e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/preceding::select[1]</value>
      <webElementGuid>d6e1d957-796b-44a2-b710-c9c4bb1c81ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/select</value>
      <webElementGuid>514a0168-34be-4191-bfe6-6ead64321782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputCity' and @name = 'city' and (text() = 'Select a city in UtahSalt Lake CityWest Valley CityProvoWest JordanOremSandyOgdenSt. GeorgeLaytonTaylorsvilleSouth JordanLehiLoganMurrayDraperBountifulRivertonRoy' or . = 'Select a city in UtahSalt Lake CityWest Valley CityProvoWest JordanOremSandyOgdenSt. GeorgeLaytonTaylorsvilleSouth JordanLehiLoganMurrayDraperBountifulRivertonRoy')]</value>
      <webElementGuid>25af49b9-a922-41be-af52-4966eba77bd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
