<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Example TexasNew YorkCaliforniaIllinoisTexasPennsylvaniaArizonaFloridaIndianaOhioNorth CarolinaMichiganTennesseeMassachusettsWashingtonColoradoDistrict of ColumbiaMarylandKentuckyOregonOklahomaWisconsinNevadaNew M</name>
   <tag></tag>
   <elementGuidId>bb22d037-59c2-48ff-8605-f8ae44a11079</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputEmergencyState']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyState</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d7ffbc33-bca1-4603-9604-8e45d01feab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>6c0c14b9-faed-430d-b156-486e6370a0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyState</value>
      <webElementGuid>9220fa4f-909a-4cc5-8757-03b2271e7afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyState</value>
      <webElementGuid>2f323fbe-11ca-4911-9199-d68bd2d03fb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Example: TexasNew YorkCaliforniaIllinoisTexasPennsylvaniaArizonaFloridaIndianaOhioNorth CarolinaMichiganTennesseeMassachusettsWashingtonColoradoDistrict of ColumbiaMarylandKentuckyOregonOklahomaWisconsinNevadaNew MexicoMissouriVirginiaGeorgiaNebraskaMinnesotaKansasLouisianaHawaiiAlaskaNew JerseyIdahoAlabamaIowaArkansasUtahRhode IslandMississippiSouth DakotaConnecticutSouth CarolinaNew HampshireNorth DakotaMontanaDelawareMaineWyomingWest VirginiaVermont</value>
      <webElementGuid>9239699a-667d-4d53-8d64-b7f6d82893f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyState&quot;)</value>
      <webElementGuid>cb8ca7e5-fbf0-49d3-b3fc-3daf2d2c71d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputEmergencyState']</value>
      <webElementGuid>c54a4c58-bb5a-409e-8ec8-8b3fa51f63a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[5]/div/div/div/div[2]/select</value>
      <webElementGuid>5829f96b-0ac2-4fac-b926-7ea34cfd33b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[10]/following::select[1]</value>
      <webElementGuid>03bd885f-d2bb-47dd-89cc-e4ab0d8300bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[11]/preceding::select[1]</value>
      <webElementGuid>afb55a19-b8f2-4691-845c-05b9861350b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[5]/div/div/div/div[2]/select</value>
      <webElementGuid>2b99e995-5dcd-4ef9-a5c7-1202e6441074</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputEmergencyState' and @name = 'emergencyState' and (text() = 'Example: TexasNew YorkCaliforniaIllinoisTexasPennsylvaniaArizonaFloridaIndianaOhioNorth CarolinaMichiganTennesseeMassachusettsWashingtonColoradoDistrict of ColumbiaMarylandKentuckyOregonOklahomaWisconsinNevadaNew MexicoMissouriVirginiaGeorgiaNebraskaMinnesotaKansasLouisianaHawaiiAlaskaNew JerseyIdahoAlabamaIowaArkansasUtahRhode IslandMississippiSouth DakotaConnecticutSouth CarolinaNew HampshireNorth DakotaMontanaDelawareMaineWyomingWest VirginiaVermont' or . = 'Example: TexasNew YorkCaliforniaIllinoisTexasPennsylvaniaArizonaFloridaIndianaOhioNorth CarolinaMichiganTennesseeMassachusettsWashingtonColoradoDistrict of ColumbiaMarylandKentuckyOregonOklahomaWisconsinNevadaNew MexicoMissouriVirginiaGeorgiaNebraskaMinnesotaKansasLouisianaHawaiiAlaskaNew JerseyIdahoAlabamaIowaArkansasUtahRhode IslandMississippiSouth DakotaConnecticutSouth CarolinaNew HampshireNorth DakotaMontanaDelawareMaineWyomingWest VirginiaVermont')]</value>
      <webElementGuid>7fd96bf0-98e4-4ab1-bd4d-50e051b4fb96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
