<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance</name>
   <tag></tag>
   <elementGuidId>8e6d08a0-8192-4bf2-a200-01df78e69bf9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='inputEmergencyPersonRelation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmergencyPersonRelation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48be025b-bfe0-425d-8b55-b902ee728328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> demographic-input</value>
      <webElementGuid>a96ab825-1f5a-4756-a5ce-268872c33102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmergencyPersonRelation</value>
      <webElementGuid>54356cb5-f7ad-4fc8-9ec8-c39fb8f5f26e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>emergencyPersonRelation</value>
      <webElementGuid>68d1cb12-4559-442b-bdeb-f1b5258002a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance</value>
      <webElementGuid>83695721-3c47-4bb7-87a4-457f6ec3b9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmergencyPersonRelation&quot;)</value>
      <webElementGuid>5aa10638-6057-418b-a653-9cf137b0a360</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='inputEmergencyPersonRelation']</value>
      <webElementGuid>dc705e71-89d6-490a-b031-4270234fb3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div[2]/div/div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>d507b973-883f-4f9f-9ccd-b9f6123eb239</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[8]/following::select[1]</value>
      <webElementGuid>993b366d-81f5-4b77-acb2-6b277b6ffec6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[9]/preceding::select[1]</value>
      <webElementGuid>92cca8a9-310f-4d02-851a-50226feeae59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>a5155951-f4f1-4e5d-a4d0-66bec738ff6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'inputEmergencyPersonRelation' and @name = 'emergencyPersonRelation' and (text() = 'Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance' or . = 'Please Select Relation SpouseSonDaughterFamilyOtherPartnerAcquaintance')]</value>
      <webElementGuid>7599a7f3-1a22-41f6-82bc-c7d8bab4c472</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
