<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_I want to type_type</name>
   <tag></tag>
   <elementGuidId>7f4a1938-9e68-424a-84a1-3f05fd79b344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='inputDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6bc3ce0b-ec53-480e-89ac-1eb548fa638d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control rounded </value>
      <webElementGuid>862a06a6-c6e9-4002-a647-f744d4dd13df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08412701-5218-4ca7-bae8-81e377608645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>be4814f8-8f02-48d4-84a0-85e36113ce8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputDescription</value>
      <webElementGuid>f4ceee96-ccb0-4981-a2bf-1d46ae112c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Please type here to build your profile and we will format automatically</value>
      <webElementGuid>3de34601-8ba3-421b-9e48-6032987c4506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>type</value>
      <webElementGuid>7a688394-f4cc-4194-b4fd-d17003f60cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputDescription&quot;)</value>
      <webElementGuid>aa18177a-96f3-4c68-9a41-ed95b8578ccb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='inputDescription']</value>
      <webElementGuid>5db81c9b-1f26-41e7-8a80-49c8321e940a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/form/div/div/textarea</value>
      <webElementGuid>6fcddaa6-582b-47b0-bbda-f3fd717d6e5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4b9bb758-2841-49b5-868d-8a9820c81b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'inputDescription' and @placeholder = 'Please type here to build your profile and we will format automatically' and @name = 'type']</value>
      <webElementGuid>b9c236a2-3d3f-49d7-acec-b58ba53d71fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
