<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Accept all cookies</name>
   <tag></tag>
   <elementGuidId>c2a8fbb7-89e5-4afa-a802-336c94ced1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ensCloseBanner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ensCloseBanner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9265b47b-d794-4f20-922c-4228f3ff96fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ensCloseBanner</value>
      <webElementGuid>59080ce5-576a-4756-bba5-af36827f9cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button raised blue</value>
      <webElementGuid>a5a1d17d-9986-47c3-9a15-167a44e9dd4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Accept all cookies</value>
      <webElementGuid>320b8441-29d2-4465-824d-00e5e6dbe3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>68b017b5-3d5d-4258-b393-924cf913049e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Accept all cookies</value>
      <webElementGuid>99391326-821c-4662-a40c-b8e7a63b2757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ensCloseBanner&quot;)</value>
      <webElementGuid>feb4c5ee-fe1f-44b9-9ca0-373679c86a8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ensCloseBanner']</value>
      <webElementGuid>52556f0c-2b25-4fe8-a953-e3fedafa3930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ensNotifyBannerInner']/div[2]/button[2]</value>
      <webElementGuid>9e1422c9-046e-4e1f-a0f4-28ac2523b808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Let me choose'])[1]/following::button[1]</value>
      <webElementGuid>42f18ab7-7245-4421-9717-2a8f6e8da29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group Cookie Notice'])[1]/following::button[2]</value>
      <webElementGuid>67faadbc-309d-40ce-a78d-26e9b4433a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Strictly Necessary'])[1]/preceding::button[1]</value>
      <webElementGuid>99b3dfac-9a01-4c81-b967-9c8a69267674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On'])[1]/preceding::button[1]</value>
      <webElementGuid>412d2fd9-40c5-48a2-b7cc-27590e583d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Accept all cookies']/parent::*</value>
      <webElementGuid>45030d62-044f-4359-b2cf-02158e98f281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/button[2]</value>
      <webElementGuid>5de1751a-7742-41c4-a649-04e988d8bbe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'ensCloseBanner' and (text() = 'Accept all cookies' or . = 'Accept all cookies')]</value>
      <webElementGuid>f2714c04-e810-4ebb-9f8f-34049a5dd018</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
